### ISSUE TITLE
Derivation of parameters etc.

### ISSUE THREAD

**Issue by philip-mach** [rajeshrinet/pyross#11]
It would be nice if you could give a method of computing parameters like beta for those who can’t work it out directly from the paper. Using you EX3 adjusted for South Africa, beta = 0.02 is a better fit to the pre-lockdown data but eyeballing is not very rigorous.

Thanks, I am finally getting somewhere with this.

**Comment by rajeshrinet** [comment]
@philip-mach this is an excellent suggestion. Thanks!

There is now an example notebook on fitting the parameter beta at https://github.com/rajeshrinet/pyross/blob/master/examples/fitParamBeta.ipynb.

**Comment by philip-mach** [comment]
Thanks. I note though you have built the value Nf into the code so it breaks if the number of cases differs from yours. I pushed a change to my fork that fixes this by putting this before Nf is first needed:

    my_data = np.genfromtxt('data/covid-cases/southafrica.txt', delimiter='', skip_header=7)
    day, cases = my_data[:,0], my_data[:,2]

    # set based on size of case data set
    Nf = cases.size
