### ISSUE TITLE
Flaw in lockdown model outputs

### ISSUE THREAD

**Issue by philip-mach** [rajeshrinet/pyross#13]
I just realised that the lockdown model can’t be right.

Each data point in the input case data is **_cumulative cases to date_**.

If you are modelling this, the **_number of cases should never drop_**. When you hit a lockdown, it should fall off the exponential trend but never decrease. If you are modelling something different then you need to modify the inputs to fit e.g. new cases in that day.

For example if you want new cases per day you need something like this:

    for i in reversed(range(cases.shape[-1])[1:]):
        cases[...,i] = cases[...,i] - cases[...,i-1]

**Comment by rajeshrinet** [comment]
@philip-mach, thanks, again. Another possible way is to get the active infected individual data, which is now possible for India with the current version of data file https://github.com/rajeshrinet/pyross/tree/master/examples/data/covid-cases
