### ISSUE TITLE
Contact Matrix for long closure fails to open

### ISSUE THREAD

**Issue by jbinary** [rajeshrinet/pyross#19]
Hi,
It seems in https://github.com/rajeshrinet/pyross/blob/master/examples/deterministic/ex4-age-structured-SIR-india-with-interventions.ipynb the last example has a flaw in contact matrix that it does not actually lift the lockdown which leads to an incorrect assumption that 49 days of lockdown is enough to stop the spread?
Thanks.

**Comment by rajeshrinet** [comment]
@jbinary it is now updated to lift the lockdown. Earlier, I had mimicked with dotted lines, what will happen if lockdown continues. But probably, as you have noted, it is better to show what happens once the lockdown is lifted. Please note that in SIR or SEIR model, once social distancing is removed the cases will grow again. So social distancing is not a tenable solution. Either herd immunity or vaccine is needed.

**Comment by jbinary** [comment]
Yes, surely. The thing is people already made a fake picture claiming 49 days enough to fight it: https://twitter.com/JBinary/status/1248726482467328003
So probably it's a very good idea to update the GIF

**Comment by ronojoy** [comment]
@jbinary many thanks for bringing this to our attention. Please could you point us to the source of the manipulated image ?

**Comment by jbinary** [comment]
I don't have the source, someone have sent it into a twitter thread but I'm pretty sure they were not the author.

**Comment by jbinary** [comment]
And actually it really was not clear from the image, so the only sin of them is they said it's from Cambridge University.

**Comment by ronojoy** [comment]
IThey also added the side captions and the erroneous interpretation that "cases will not increase". This is *not* something we have said in our paper. Everything in this repository is under MIT license but that does not absolve the users from being irresponsible.

**Comment by jbinary** [comment]
Absolutely. We are lucky though: https://www.indiatoday.in/india/story/coronavirus-lockdown-india-cambridge-mathematical-model-extension-1661321-2020-03-30

**Comment by jbinary** [comment]
Oh wait sorry, it's not the source. I'll try to ask the guy where did he take it from.

**Comment by nbfigueroa** [comment]
Just a suggestion, in order to avoid any further misinterpretations of your plots and predictions, perhaps you should also lift the lockdown for the three closure case; i.e.
```python
def contactMatrix(t):
    if t<21:
        xx = C
    elif 21<=t<42:
        xx = CH
    elif 42<=t<47:
        xx = C
    elif 47<=t<75:
        xx = CH
    elif 75<=t<80:
        xx = C
    elif 80<=t<98:
        xx = CH
    else:
        xx = C
    return xx
```
and maybe increase the simulation time to >98. This way for all the simulated scenarios the plots will represent what really happens when the lockdowns are lifted, without any assumptions. This will hopefully avoid tweets like the one @jbinary pointed out. 

Best and great work!
Nadia

**Comment by ronojoy** [comment]
@nbfigueroa thanks for this suggestion (we'll keep this in mind for future work) and for your kind words. All the best!
