### ISSUE TITLE
SIR and SEIR model for Kerala

### ISSUE THREAD

**Issue by technOslerphile** [rajeshrinet/pyross#21]
Hi,
I tweaked some stuffs, added Kerala data, fitted till data available on April 11th and simulated both SIR and SEIR models considering only the current 35 days lockdown. Both SIR and SEIR models says this lockdown is enough to contain the disease. 
[KERALA.zip](https://github.com/rajeshrinet/pyross/files/4466591/KERALA.zip)
Although I have significantly tweaked the contactMatrix, recovery rates and other parameters. Would like you to take a look at the notebook. The notebook and the data are attached herewith. I am planning to blog about this, but since you are the developers of the model and the python package, I believe it's better to avoid any misunderstandings/confusions, if applicable :-)

**Comment by Nikoloz19** [comment]
Hi,

I am trying to do the same thing for Georgia. I have also changed the contact matrix accordingly to the lockdowns, and the results look satisfying. The only problem is curve fitting. I see that gIa, gIs, alpha, fsa in your document are different from India. For the Georgian case, we know that gIa and gIs are 1./14 but I am not sure how to calculate alpha and fsa. Could you please tell me how did you do the calculations? and what would be the best way to approach the curve fitting problem? 

Thank you in advance!

**Comment by Nikoloz19** [comment]
Hi,

I am trying to do the same thing for Georgia. I have also changed the contact matrix accordingly to the lockdowns, and the results look satisfying. The only problem is curve fitting. I see that gIa, gIs, alpha, fsa in your document are different from India. For the Georgian case, we know that gIa and gIs are 1./14 but I am not sure how to calculate alpha and fsa. Could you please tell me how did you do the calculations? and what would be the best way to approach the curve fitting problem?

Thank you in advance!

**Comment by ronojoy** [comment]
@technOslerphile @Nikoloz19,  the fitting in the India paper was done only for the infectiousness parameter beta. The proper way to estimate all these is by Bayesian inference. We are working on that now and it should be ready by early next week. That will have proper uncertainty estimates rather than the modal point estimates of our current fitting method. As a caveat, it makes sense to fit data to compartment models only if the transmission is taking place under well-mixed conditions. The case numbers for both Kerala and Georgia seem too low for this to hold.

**Comment by technOslerphile** [comment]
@ronojoy Thanks for the response. After I posted this, I continued to explore the model fitting to estimate beta and found that the model fitting didn't converge for Kerala a couple of days ago.I tried this with multiple other states and none of them seemed to converge. So I had decided not to write anything on this for now. I presumed it had to do with the data. Thanks for confirmation. Would love to see the Bayesian inference estimation.

**Comment by Nikoloz19** [comment]
@ronojoy  Hello, I hope you are doing well. I apologize to trouble you but wanted to ask regarding the Bayesian inference. Could please tell me approximately when will it be added to the model? So far our data fits the forecasted curve when the contact matrix is C. We would love to try playing around with different lockdown scenarios to analyze how it will be better to proceed regarding their durations. When we change the matrix from C the forecast and data curve are not fitted and hope Bayesian inference could help.

**Comment by ronojoy** [comment]
@Nikoloz19 we already have inference and Bayesian forecasts in the library now. There are examples of each in the notebooks but I will put together a notebook later today which combines everything into a single notebook. The main steps would be (a) select an epidemiological model (b) fit the model to the data to estimate the parameters and their uncertainties (c) simulate the epidemic with parameters drawn from the posterior distribution to obtain a Bayesian forecast and (d) apply interventions to obtain a Bayesian forecast of efficacy. I will post an update on this issue when done.

**Comment by ronojoy** [comment]
@Nikoloz19 and  @technOslerphile: we now have a complete [inference + forecast notebook ](https://github.com/rajeshrinet/pyross/blob/master/examples/forecast/ex05%20-%20SIR%20-%20inference%20%2B%20forecast.ipynb) available, thanks to @juliankappler @Irene-Li @rajeshrinet and others in our group. I hope this will be of help in working out Bayesian forecasts for each of the demographics you are interested in.
