### ISSUE TITLE
pyross model import error

### ISSUE THREAD

**Issue by Rukhsan** [rajeshrinet/pyross#24]
Hi. This is Rukhsan here. I want to use find the effect of social distancing on the Covid19 transmission. I successfully installed the library. But when I try to import any model, I get import error. Similary I get errors when I try to import contactMatix and control etc. Can you please let me know how should I sort this out. Thanks

**Comment by rajeshrinet** [comment]
@Rukhsan can you go to the example folder and run one of the examples and share the screenshot. 

See also https://github.com/rajeshrinet/pyross/issues/3

**Comment by Rukhsan** [comment]
@rajeshrinet  Thanks for your reply and support. I tried running several examples from the examples folder. But your answer suggests that I need to change the folder. Do I need to change my current directory to the one where pyross is installed and then do the import again.

**Comment by rajeshrinet** [comment]
@Rukhsan please can you pull the latest version. Now it can be imported from anywhere. Thanks

**Comment by Rukhsan** [comment]
@rajeshrinet Happy to know about that update. I will get updated version installed and hopefully it works with me.
