### ISSUE TITLE
Issue in Pyross

### ISSUE THREAD

**Issue by shaliniharkar** [rajeshrinet/pyross#25]
Hello, 
I am Shalini. First of all i would like to congratulate you all for this wonderful paper. I found this paper very very useful for my work and started the same in more deep. 
So, while I was exploring the implementation part of pyross , I am facing some critical issues in loading modules. 
Firstly i installed the latest version of the Pyross the way you have suggested in the github and tried implementing one of the module in example folder but unfortunately it says the module is not such attribute.  
It would be of great help if you can help me to solve the issue.  Attaching hereby the screenshot of the error and looking forward to hear from you.
![Error in pyross](https://user-images.githubusercontent.com/31668503/80797504-a155f180-8bbf-11ea-8d12-e48a7f7a0476.jpg)

Thanks & Regards, 
Shalini

**Comment by rajeshrinet** [comment]
@shaliniharkar thanks very much for your kind words. It is very much appreciated by us. 

Please can you pull the latest version? And then go the example folder. I want you to run [this example](https://github.com/rajeshrinet/pyross/blob/master/examples/deterministic/ex01-SIR.ipynb) and share the screenshot of the first three cells. Thanks

**Comment by rajeshrinet** [comment]
@shaliniharkar please also ensure that you have installed all the [requirements](https://github.com/rajeshrinet/pyross/blob/master/requirements.txt). Thanks
