### ISSUE TITLE
Difference between progression rate from E to A and recovery rates from E in ex12-SEAIRandSEAIRQ

### ISSUE THREAD

**Issue by Mouvoh** [rajeshrinet/pyross#28]
Hello evrybody, during my models research I have checked out the examples in the pyross module and I wonder what is the the difference between **progression rate from E to A** and **recovery rates from E in ex12-SEAIRandSEAIRQ.** 
As far as I know gE ( gamma) is the inverse of the length of the incubation but in the script two values are given for the same parameter :  1 and 0.04.
Is this an error or did I have a bad comprehension of this parameter ? Even if it is the case, there's still the problem of why two values for the same variable ? 
Thanks in advance !
![4](https://user-images.githubusercontent.com/62729599/81123958-d0ec5d00-8f23-11ea-9ffe-66cbd115d1e8.png)
![3](https://user-images.githubusercontent.com/62729599/81123959-d184f380-8f23-11ea-9568-4e4886b50031.png)

**Comment by rajeshrinet** [comment]
@Mouvoh thanks for this. Clearly only the latter value of gE has been used in the code. As you have already added the screenshot of our equation, it is clear the gE is the rate to go from E to A or the inverse of the incubation period. This can also be called the average recovery rate from E and the progression to A. We are in the process of updating comments on all examples and thanks for pointing this out. We will now use a single standard notation now. I have also updated the example. Hope this helps.

**Comment by Mouvoh** [comment]
Thanks you too a lot, it is a pleasure to help !
