### ISSUE TITLE
Pyross Installation

### ISSUE THREAD

**Issue by wajoor** [rajeshrinet/pyross#32]
Hi Rajeshrinet,
I have tried to install pyros over the last two days with no luck. Indeed it is a painful journey. I did look at pyros issue posts. 

Would you please help. Many thanks in advance. Also I sincerely apologize for this long post…

I have Python 3.6.5, Cython 0.28.2, Conda 4.8.2

Here is a summary of what I did:
1. git clone https://github.com/rajeshrinet/pyross.git
2. cd pyross
3. for (>>> make env): conda env create  -f environment.yml
4. conda activate pyros
5. pyross package installation (3 ways all negative result)
**5.1 conda install pyross**: Error message (PackageNotFoundError)
--------------------------- cmd screen
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
PackagesNotFoundError: The following packages are not available from current channels:
  - pyross
Current channels:
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch
To search for alternate channels that may provide the conda package you're
looking for, navigate to
    https://anaconda.org
and use the search bar at the top of the page.
--------------------------- cmd screen end

**5.2 pip install pyross**: 2 error messages: (1) Building wheels for pyros (PEP 517) … error, (2) Building 'pyross.contactMatrix' extension
 error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
Failed to build pyros
--------------------------- cmd screen
(pyross) C:\Users\wafeeq.ajoor\pyross>pip install pyross
Collecting pyross
  Using cached pyross-1.1.9.tar.gz (2.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: ipython in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\envs\pyross\lib\site-packages (from pyross) (7.16.1)
Requirement already satisfied: cma in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\envs\pyross\lib\site-packages (from pyross) (3.0.3)
Collecting jupyter
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Requirement already satisfied: cython in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\envs\pyross\lib\site-packages (from pyross) (0.29.20)
:
:
:
Requirement already satisfied: zipp>=0.5 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\envs\pyross\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema!=2.5.0,>=2.4->nbformat>=4.4->nbconvert->pyross) (3.1.0)
Building wheels for collected packages: pyross
  Building wheel for pyross (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\python.exe' 'C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\WAFEEQ~1.AJO\AppData\Local\Temp\tmpfi5u52l7'
       cwd: C:\Users\WAFEEQ~1.AJO\AppData\Local\Temp\pip-install-pt6fzrk1\pyross
  Complete output (12 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pyross
  copying pyross\utils_python.py -> build\lib.win-amd64-3.7\pyross
  copying pyross\__init__.py -> build\lib.win-amd64-3.7\pyross
  copying pyross\deterministic.pxd -> build\lib.win-amd64-3.7\pyross
  running build_ext
  building 'pyross.contactMatrix' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/

  ERROR: Failed building wheel for pyross
Failed to build pyross
ERROR: Could not build wheels for pyross which use PEP 517 and cannot be installed directly
--------------------------- cmd screen end

**5.3 python setup.py install**: error messages: Building 'pyross.contactMatrix' extension
 error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
--------------------------- cmd screen
(pyross) C:\Users\wafeeq.ajoor\pyross>python setup.py install
running install
running bdist_egg
running egg_info
writing pyross.egg-info\PKG-INFO
writing dependency_links to pyross.egg-info\dependency_links.txt
writing requirements to pyross.egg-info\requires.txt
writing top-level names to pyross.egg-info\top_level.txt
reading manifest file 'pyross.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pyross.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'pyross.contactMatrix' extension
error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
--------------------------- cmd screen end

6. I focused on #5.3 (python setup.py install), trying to resolve the issue with no luck.
6.1 I downloaded and installed Visual C++ Build Test from the following link (Use this link to download and install Visual C++ 2015 Build Tools. It will automatically download visualcppbuildtools_full.exe and install Visual C++ 14.0 without actually installing Visual Studio): https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat/60396650#60396650

6.2 But still getting above “Microsoft Visual C++ 14.0 is required” error message. 
I thought “Path” is the issue. Here is snapshot of my system “Path”:
--------------------------- cmd screen
(pyross) C:\Users\wafeeq.ajoor\pyross>echo %PATH%
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\Library\mingw-w64\bin;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\Library\usr\bin;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\Library\bin;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\Scripts;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\envs\pyross\bin;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\condabin;
C:\Windows\system32;
C:\Windows;
C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0;
C:\Program Files\Git\cmd;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3;
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0;
C:\Program Files\Git\cmd;
C:\Program Files\Microsoft VS Code\bin;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3;
C:\Users\wafeeq.ajoor\AppData\Local\Microsoft\WindowsApps;
.;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\Scripts;
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3"
--------------------------- cmd screen end

How can I be sure that “pyross setup.py” have access to Microsoft Visual C++ 14.0 Buildtools? What seem the problem, if otherwise?

Regards,
Wafeeq

**Comment by rajeshrinet** [comment]
@wajoor, windows is not supported in the current codebase. We will let you know once support for windows is added. For now, you can try the  linux virtual machine under windows or the windows linux subsystem.

Alternatively, please consider using the [binder](https://mybinder.org/v2/gh/rajeshrinet/pyross/master?filepath=binder). It works identically to a local installation.

**Comment by rajeshrinet** [comment]
@wajoor I can confirm that PyRoss can now be compiled for Windows. I used Github workflows to check this. It can be reproduced by following [this workflow](https://github.com/rajeshrinet/pyross/blob/master/.github/workflows/build-test-windows.yml.). 

See our latest run, which builds and test the installation [at this link.](https://github.com/rajeshrinet/pyross/runs/820120970)

**Comment by wajoor** [comment]
Hi Rajeshrinet,

Deep and sincere appreciation for reply and support. As I am newbie to Github, I am not sure what to do next. 

Do I download this workflow (https://github.com/rajeshrinet/pyross/actions/runs/152009551/workflow) into my local machine  at C:\Users\wafeeq.ajoor\pyross\.github\workflows and execute "python setup.py install" or there is another way to run this workflow from github to install pyross on my windows desktop? would you please advice.
Regards,
Wafeeq

**Comment by rajeshrinet** [comment]
@wajoor please try:

```bash
>> pip install pyross
```

**Comment by wajoor** [comment]
Hi Rajeshrinet,

First of all thank you very much for updating pyross to run on windows. I tried "pip install pyros" and got below errors: PEP 517, Wheel, and "Microsoft Visual C++ 14.0" is required" as shown below. 

I noticed that that pyross 1.2.5 has files and uses Python 3.7 :
pyross-1.2.5-cp37-cp37m-macosx_10_9_x86_64.whl (5.7 MB), Wheel, cp37 
pyross-1.2.5-py3.7-macosx-10.9-x86_64.egg (5.7 MB), Egg, 3.7 
pyross-1.2.5.tar.gz (2.6 MB), Source

My current versions are Python 3.6.5, Cython 0.28.2, Conda 4.8.2. Do I need to upgrade to Python 3.7 as both above Wheel and Egg uses Python 3.7?

Would you please advice.

**************************cmd screenshot
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\wafeeq.ajoor>pip install pyross
Collecting pyross
  Using cached pyross-1.2.5.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: nestle in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages\nestle-0.2.0-py3.6.egg (from pyross) (0.2.0)
Requirement already satisfied: cython in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (0.28.2)
Requirement already satisfied: xlrd in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.1.0)
Requirement already satisfied: cma in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (3.0.3)
Requirement already satisfied: numpy in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.14.3)
Requirement already satisfied: sympy in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.1.1)
Requirement already satisfied: nlopt in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (2.6.1)
Requirement already satisfied: pandas in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (0.23.0)
Requirement already satisfied: matplotlib in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (2.2.2)
Requirement already satisfied: scipy in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.1.0)
Requirement already satisfied: pathos in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (0.2.5)
Requirement already satisfied: pytz>=2011k in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->pyross) (2018.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->pyross) (2.7.3)
Requirement already satisfied: cycler>=0.10 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (2.2.0)
Requirement already satisfied: six>=1.10 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (1.0.1)
Requirement already satisfied: ppft>=1.6.6.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (1.6.6.1)
Requirement already satisfied: multiprocess>=0.70.9 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (0.70.9)
Requirement already satisfied: pox>=0.2.7 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (0.2.7)
Requirement already satisfied: dill>=0.3.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (0.3.1.1)
Requirement already satisfied: setuptools in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->pyross) (47.3.1.post20200622)
Building wheels for collected packages: pyross
  Building wheel for pyross (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\python.exe' 'c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\WAFEEQ~1.AJO\AppData\Local\Temp\tmppztn9c11'
       cwd: C:\Users\WAFEEQ~1.AJO\AppData\Local\Temp\pip-install-3hchw51e\pyross
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pyross
  copying pyross\utils_python.py -> build\lib.win-amd64-3.6\pyross
  copying pyross\__init__.py -> build\lib.win-amd64-3.6\pyross
  running egg_info
  writing pyross.egg-info\PKG-INFO
  writing dependency_links to pyross.egg-info\dependency_links.txt
  writing requirements to pyross.egg-info\requires.txt
  writing top-level names to pyross.egg-info\top_level.txt
  reading manifest file 'pyross.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pyross.egg-info\SOURCES.txt'
  copying pyross\contactMatrix.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\contactMatrix.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\control.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\control.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\deterministic.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\deterministic.pxd -> build\lib.win-amd64-3.6\pyross
  copying pyross\deterministic.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\forecast.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\forecast.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\hybrid.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\hybrid.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\inference.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\inference.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\stochastic.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\stochastic.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\utils.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\utils.pyx -> build\lib.win-amd64-3.6\pyross
  running build_ext
  building 'pyross.contactMatrix' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyross
Failed to build pyross
ERROR: Could not build wheels for pyross which use PEP 517 and cannot be installed directly
**************************cmd screenshot end

**Comment by rajeshrinet** [comment]
@wajoor please install https://visualstudio.microsoft.com/visual-cpp-build-tools/

Alternatively, this solution might be useful: https://www.scivision.co/python-windows-visual-c-14-required

Any Python 3.4+ should be fine to run PyRoss.

**Comment by wajoor** [comment]
Hi Rajeshrinet,

I installed Microsoft Visual Studio. But still get same error message (shown below at cmd screenshot)

Here is summary what I did:
1.	Downloaded (vs_buildtools__329949629.1593274981) from: https://visualstudio.microsoft.com/visual-cpp-build-tools/

2.	Installed: Visual Studio 2019 version 16.6.3 NEW (https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.6.3). 

At Installing windows, I selected below items:
Workload: Desktop & Mobile
C++ Build Tools

On right pane/frame >>> 
Installation details
    MSBuild Tools
    C++ build tools
Included
       C++ Build Tools core features
       C++ 2019 Redistributable Update
   Optional
 MSVC v142 - VS 2019 C++ x64/x86 build tools (v14.26)
 Windows 10 SDK (10.0.18362.0)
 C++ CMake tools for Windows
 Testing tools core features - Build Tools
 C++ AddressSanitizer (Experimental)
 C++ ATL for latest v142 build tools (x86 & x64)
 C++ MFC for latest v142 build tools (x86 & x64)
 C++/CLI support for v142 build tools (14.26)
 C++ Modules for v142 build tools (x64/x86 – expe

3.	Microsoft Visual Studio2019 was installed at location:
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools

4.	I checked Environment Variables
User variables: 
Path
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files\Git\cmd
C:\Program Files\Microsoft VS Code\bin
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3
C:\Users\wafeeq.ajoor\AppData\Local\Microsoft\WindowsApps
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3\Scripts\

System Variables:
Path
%SystemRoot%\system32
%SystemRoot%
%SystemRoot%\System32\Wbem
%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\
C:\Program Files\Git\cmd
C:\Users\wafeeq.ajoor\AppData\Local\Continuum\anaconda3
PATHEXT
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

PSModulePath
%ProgramFiles%\WindowsPowerShell\Modules
%SystemRoot%\system32\WindowsPowerShell\v1.0\Modules

VS140COMNTOOLS
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\

Q: How can be sure that Microsoft Visual Studio is installed? 

Q: Is above path ok? I don't see: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools

Q: Shall I replace above variable (VS140COMNTOOLS): 
VS140COMNTOOLS = C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
with: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools

Many thanks for your efforts and support.

**************************cmd screenshot
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\wafeeq.ajoor>pip install pyross
Collecting pyross
  Using cached pyross-1.2.5.tar.gz (2.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cython in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (0.28.2)
Requirement already satisfied: nestle in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages\nestle-0.2.0-py3.6.egg (from pyross) (0.2.0)
Requirement already satisfied: pathos in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (0.2.5)
Requirement already satisfied: nlopt in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (2.6.1)
Requirement already satisfied: sympy in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.1.1)
Requirement already satisfied: pandas in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (0.23.0)
Requirement already satisfied: scipy in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.1.0)
Requirement already satisfied: cma in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (3.0.3)
Requirement already satisfied: matplotlib in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (2.2.2)
Requirement already satisfied: numpy in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.14.3)
Requirement already satisfied: xlrd in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pyross) (1.1.0)
Requirement already satisfied: pox>=0.2.7 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (0.2.7)
Requirement already satisfied: ppft>=1.6.6.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (1.6.6.1)
Requirement already satisfied: dill>=0.3.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (0.3.1.1)
Requirement already satisfied: multiprocess>=0.70.9 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pathos->pyross) (0.70.9)
Requirement already satisfied: pytz>=2011k in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->pyross) (2018.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from pandas->pyross) (2.7.3)
Requirement already satisfied: cycler>=0.10 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (2.2.0)
Requirement already satisfied: six>=1.10 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from matplotlib->pyross) (1.0.1)
Requirement already satisfied: setuptools in c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib->pyross) (47.3.1.post20200622)
Building wheels for collected packages: pyross
  Building wheel for pyross (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\python.exe' 'c:\users\wafeeq.ajoor\appdata\local\continuum\anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\WAFEEQ~1.AJO\AppData\Local\Temp\tmp4kdnqzp0'
       cwd: C:\Users\WAFEEQ~1.AJO\AppData\Local\Temp\pip-install-m1rb9p03\pyross
  Complete output (36 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.6
  creating build\lib.win-amd64-3.6\pyross
  copying pyross\utils_python.py -> build\lib.win-amd64-3.6\pyross
  copying pyross\__init__.py -> build\lib.win-amd64-3.6\pyross
  running egg_info
  writing pyross.egg-info\PKG-INFO
  writing dependency_links to pyross.egg-info\dependency_links.txt
  writing requirements to pyross.egg-info\requires.txt
  writing top-level names to pyross.egg-info\top_level.txt
  reading manifest file 'pyross.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pyross.egg-info\SOURCES.txt'
  copying pyross\contactMatrix.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\contactMatrix.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\control.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\control.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\deterministic.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\deterministic.pxd -> build\lib.win-amd64-3.6\pyross
  copying pyross\deterministic.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\forecast.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\forecast.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\hybrid.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\hybrid.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\inference.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\inference.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\stochastic.cpp -> build\lib.win-amd64-3.6\pyross
  copying pyross\stochastic.pyx -> build\lib.win-amd64-3.6\pyross
  copying pyross\utils.c -> build\lib.win-amd64-3.6\pyross
  copying pyross\utils.pyx -> build\lib.win-amd64-3.6\pyross
  running build_ext
  building 'pyross.contactMatrix' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for pyross
Failed to build pyross
ERROR: Could not build wheels for pyross which use PEP 517 and cannot be installed directly
**************************cmd screenshot end

**Comment by rajeshrinet** [comment]
@wajoor , unfortunately, I do not understand the paths in windows well enough, and thus, I find myself unable to help. It is interesting to note that the [workflow](https://github.com/rajeshrinet/pyross/actions/runs/152486810/workflow) I used for windows using [GitHub actions](https://github.com/features/actions) works fine. Can you also try using the installation instructions in the [README](https://github.com/rajeshrinet/pyross#installation) other than pip? If that too does not work, then, please try running PyRoss using possibilities listed in this [comment](https://github.com/rajeshrinet/pyross/issues/32#issuecomment-651241313).
