### ISSUE TITLE
Supporting time-varying model parameters

### ISSUE THREAD

**Issue by amir-ghasemi** [rajeshrinet/pyross#36]
Hi,

Any plans or possibility to support time varying model parameters that depend on other external data? Is this best achieved by modifying the contact matrix during the simulation?

Thanks!

**Comment by rajeshrinet** [comment]
Hi @amir-ghasemi,

It is indeed best achieved by subsuming it in the contact matrix for the specific case of beta. See also [this example](https://github.com/rajeshrinet/pyross/blob/master/examples/deterministic/ex18-Spp-time_dependent_parameters.ipynb) which shows how an arbitrary time-dependence of parameters can be specified.
