### ISSUE TITLE
Documentation of fsa and SEkIkIkR in readthedocs

### ISSUE THREAD

**Issue by shermanlo77** [rajeshrinet/pyross#37]
I think there is an error on the description for the parameter _fsa_ in the [readthedocs](https://pyross.readthedocs.io/en/latest/deterministic.html)?

> _fsa: float, np.array (M,)_
> Fraction by which symptomatic individuals self isolate.

should be corrected to

> _fsa: float, np.array (M,)_
> Fraction of symptomatic individuals who *do not* self isolate.

because a value of _fsa=1_ should mean that all symptomatic infectives are in contact with the general population.

Also, I think there is a typo in the description of the parameters for SEkIkIkR because it is missing _fsa_ as a parameter?

Thank you!

**Comment by rajeshrinet** [comment]
@shermanlo77, thanks very much for spotting these. The documentation has now been updated.
