### ISSUE TITLE
Using PyRoss for a vaccination model

### ISSUE THREAD

**Issue by ahb48** [rajeshrinet/pyross#39]
Hi,

I would like to use your PyRoss modelling code to implement an SEIRV model to do some inference on vaccination strategies and the reopening of schools. 

As far as I’m aware, a vaccination class (where individuals can still become infected) does not seem to be readily implementable. Is this the case at present – i.e. there cannot be more than one “susceptible” class?

I was hoping you could tell me how easy this would be to either implement myself using PyRoss or whether this is something your group have been working on to include in the code but it has not yet been released?

Thanks in advance,
Abby

**Comment by ppietzonka** [comment]
Hi Abby,

Thank you for your interest in PyRoss. Well spotted, the official version of PyRoss allows in the model specification of the Spp class only a single susceptible class. This is indeed a limitation when it comes to building models for vaccinations. 

We are therefore developing a new class, dubbed Xpp, that allows for arbitrary susceptible classes. There, one specifies for an infection term not only the infectious class but also the relevant susceptible class. This works well so far, however, the feature is not yet properly documented and therefore hidden in the branch Xpp of the PyRoss project (https://github.com/rajeshrinet/pyross/tree/Xpp). You can switch to this branch and recompile PyRoss. I have just uploaded an example notebook with vaccinations (https://github.com/rajeshrinet/pyross/blob/Xpp/examples/stochastic/ex10-Xpp_vaccinations.ipynb), I hope the Xpp class will be self-explaining there.

We plan to merge Xpp soon into the master branch.

Wishing you success with your project,
Patrick

**Comment by ahb48** [comment]
Hi Patrick,

Thanks very much. I think this will probably work well.

All the best,
Abby

**Comment by rajeshrinet** [comment]
Hi Abby,

We have now merged the `Xpp` branch to the `master` branch. The class `Xpp` has been renamed to `Model`. Please find included below links to updated example notebooks,

* [Deterministic simulations](https://github.com/rajeshrinet/pyross/blob/master/examples/deterministic/ex01b_Model.ipynb)
* [Stochastic simulations](https://github.com/rajeshrinet/pyross/blob/master/examples/stochastic/ex01b_Model.ipynb)

Best,
Rajesh

**Comment by ahb48** [comment]
Hi Rajesh,

Thanks very much. This will be very useful!

Best,
Abby
