### ISSUE TITLE
[WinError 2] Le fichier spécifié est introuvable

### ISSUE THREAD

**Issue by aminemosbah** [rajeshrinet/pyross#4]
%%capture
## compile PyRoss for this notebook
import os
owd = os.getcwd()
os.chdir('../')
%run setup.py install
os.chdir(owd)

D:\Anaconda3\envs\causal_net\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    995                                          env,
    996                                          os.fspath(cwd) if cwd is not None else None,
--> 997                                          startupinfo)
    998             finally:
    999                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable

**Comment by rajeshrinet** [comment]
@aminemosbah are you running it on Windows. We are aware that our compilation is having some issues with Windows. Please can I suggest to use the binder while we fix the problem specific to Windows?

Please click on the Binder link in the README.md. Be patient while Binder loads but after that, there is no difference in running from your own computer.

**Comment by aminemosbah** [comment]
thanks, i m trying to run the exemple on collab

 and here is the issue 

AttributeError                            Traceback (most recent call last)
<ipython-input-12-4102f97d3a6e> in <module>()
     22 
     23 # start simulation
---> 24 model = pyross.models.SIR(S_0, Ia_0, Is_0, alpha, beta, gamma, fsa, M, Ni, Tf)
     25 Nf=8000; filename='this.mat'
     26 model.simulate(CTS, Nf, filename)

AttributeError: module 'pyross' has no attribute 'models'
any suggestion?

**Comment by rajeshrinet** [comment]
There is now a solution for the above problems at https://github.com/rajeshrinet/pyross/issues/14
