### ISSUE TITLE
Jupyter Binder not working

### ISSUE THREAD

**Issue by dwilson10** [rajeshrinet/pyross#42]
I've been trying to use https://mybinder.org/v2/gh/rajeshrinet/pyross/master?filepath=binder but it's currently not operating properly, any suggestions?

**Comment by richvirology** [comment]
I'm having the same issue with a fresh install of pyross that seems to also occur with binder.  It seems to be a depreciated way of calling eigen from scipy.sparse.linalg in pyross/utils.pyx

**Comment by rajeshrinet** [comment]
Thanks to both of you for flagging this. It should work now in the latest version. If binder is continuing to use the older version, then force it to use latest one by using `pip install pyross==2.2.0`
