### ISSUE TITLE
Data columns in case files

### ISSUE THREAD

**Issue by philip-mach** [rajeshrinet/pyross#7]
I noticed the India data has an extra column compared with the China and Italy files. Can you clarify? Maybe a README in the data covid-cases directory?

Thanks.

**Comment by rajeshrinet** [comment]
@philip-mach thanks for pointing this out. There is now a readme.

The file for India has three columns: days since the first case, date, the number of infected individuals. 

The files for China and Italy has two columns: date and number of infected individuals

**Comment by Mouvoh** [comment]
Hello Sir @rajeshrinet for the SIR and other examples based on India, can we use The Italy file as given or do we have to add the third column please ?

**Comment by philip-mach** [comment]
Since it is running the same code there is no reason to believe that any other country will not need the missing column. I added it for South Africa to make it work. However: things have moved on since then and each country seems to have a different data format.

Look in the Notebook for different countries for a line that starts something lke
